/**
 * Receipt Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AggregationType = {
    Day: 'day',
    Month: 'month',
    Year: 'year'
} as const;
export type AggregationType = typeof AggregationType[keyof typeof AggregationType];

