/**
 * Receipt Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarketAverageSpent } from './marketAverageSpent';


export interface MarketAverageSpentList { 
    markets: Array<MarketAverageSpent>;
}

