/**
 * Receipt Tracker API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MarketTotalSpent} from './marketTotalSpent';


export interface MarketTotalSpentList {
    markets: Array<MarketTotalSpent>;
}

