/**
 * Receipt Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarketTotalReceipts } from './marketTotalReceipts';


export interface MarketTotalReceiptsList { 
    markets: Array<MarketTotalReceipts>;
}

