/**
 * Receipt Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReceiptItemUpdateRequest { 
    id?: number | null;
    name: string;
    unit_price: number;
    quantity: number;
    unit: string;
}

