/**
 * Receipt Tracker API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ReceiptItemUpdateRequest} from './receiptItemUpdateRequest';


export interface ReceiptUpdateRequest {
    date?: string | null;
    receipt_number?: string | null;
    market_id?: number | null;
    postal_code?: string | null;
    city?: string | null;
    street_name?: string | null;
    street_number?: string | null;
    items?: Array<ReceiptItemUpdateRequest> | null;
}

