/**
 * Receipt Tracker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptItemCreateRequest } from './receiptItemCreateRequest';


export interface ReceiptCreateRequest { 
    date: string;
    receipt_number: string;
    market_id: number;
    image_path: string;
    original_filename: string;
    postal_code: string;
    city: string;
    street_name: string;
    street_number: string;
    user_id?: number | null;
    items?: Array<ReceiptItemCreateRequest> | null;
}

