/**
 * Receipt Tracker API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {UserOut} from './userOut';


export interface UserListOut {
    users: Array<UserOut>;
    skip: number;
    page_size: number;
    total: number;
}

