/**
 * Receipt Tracker API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Role} from './role';


export interface UserUpdateRequest {
    email?: string | null;
    fullname?: string | null;
    profile_picture?: string | null;
    disabled?: boolean | null;
    roles?: Array<Role> | null;
}

